from tkinter import *
login_window =Tk()
login_window.geometry("450x250")
login_window.title("Address Entry Form")
first_name = Label(login_window, text="First Name:").place(x=30, y=10)
entry1 = Entry(login_window, width=50).place(x=100, y=10)
last_name = Label(login_window,text="Last Name:").place(x=30,y=30)
entry2 = Entry(login_window,width=50).place(x=100, y =30)
address_line_1 = Label(login_window,text="Address Line 1:").place(x=10,y=50)
entry3 = Entry(login_window, width=50).place(x=100, y=50)
address_line_2 = Label(login_window,text="Address Line 2:").place(x=10,y=70)
entry4 = Entry(login_window, width=50).place(x=100, y=70)
city = Label(login_window,text = "City:").place(x=65,y=90)
entry5 = Entry(login_window, width=50).place(x=100, y=90)
state_province = Label(login_window,text="State/Province:").place(x=10,y=110)
entry6 = Entry(login_window, width=50).place(x=100, y=110)
postal_code = Label(login_window,text="Postal Code:").place(x=25,y=130)
entry6 = Entry(login_window, width=50).place(x=100,y=130)
country = Label(login_window,text="Country:").place(x=45, y = 150)
entry7 = Entry(login_window,width=50).place(x=100,y=150)
clear = Button(login_window,text="Clear",width=10,height=1).place(x=240,y=180)
submit = Button(login_window,text="Submit",width=10,height=1).place(x=325,y=180)
login_window.mainloop()
