from tkinter import *
login_window= Tk()
login_window.geometry("400x250")
login_window.title("First-program")
username = Label(login_window, text="username: ").pack()
entry1 = Entry(login_window, width=30).pack()
password = Label(login_window, text="password: ").pack()
entry2 = Entry(login_window, width=30).pack()
login = Button(login_window,text="login", width=10).pack()
login_window.mainloop()